<?php
/**
 * MetaTagTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhotoShelter\Dev
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhotoShelter API v4
 *
 * # PhotoShelter API v4 definition
 *
 * OpenAPI spec version: Anthony
 * Contact: api-support@photoshelter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhotoShelter\Dev;

/**
 * MetaTagTest Class Doc Comment
 *
 * @category    Class
 * @description MetaTag
 * @package     PhotoShelter\Dev
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MetaTagTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MetaTag"
     */
    public function testMetaTag()
    {
    }

    /**
     * Test attribute "copyright"
     */
    public function testPropertyCopyright()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "rate_limit_limit"
     */
    public function testPropertyRateLimitLimit()
    {
    }

    /**
     * Test attribute "rate_limit_current"
     */
    public function testPropertyRateLimitCurrent()
    {
    }

    /**
     * Test attribute "rate_limit_expires"
     */
    public function testPropertyRateLimitExpires()
    {
    }
}
