stages:
  -
    name: linting
  -
    name: syntax-validation
  -
    name: contract-testing
  -
    name: documentation
dist: xenial
language: node_js
node_js:
  - '9'
before_install:
  - 'npm install'
  - 'npm install speccy -g'
  - 'npm install -g swagger-cli'
  - 'npm install redoc --save'
  - 'npm install -g create-openapi-repo'
  - 'npm install -g @stoplight/prism-cli'
  - 'npm install -g dredd'
  - 'sudo apt-get install expect'
  - 'sudo apt-get install curl'
before_script:
  - 'sudo chmod 755 run-redoc.exp'
  - 'cat /etc/hosts'
# How to make this happen ? so each view can be dynamicaly setup
 # - 'culr -I -v http://anthony.dev.bitshelter.com:8090/psapi/v4.0/gallery/G00006n1vPRXpsjw?api_key=A018guq6BbY&include=images:page(1):per_page(2):sort_dir(lambda):sort_by(alpha|teta)&date_format=iso8601&page=2&per_page=2&include=link'
  - 'curl -I -v https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/.travis.yml'
after_script:
  - 'wget https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/index.html'
  - 'ls -la'
cache:
  directories:
    - node_modules
jobs:
  include:
    -
      stage: linting
      verbose: true
      script:
        - 'speccy lint -v definitions/photoshelter.json'
        - 'sleep 3'
      install: skip
    -
      stage: syntax-validation
      verbose: true
      script:
        - 'swagger-cli validate -d --no-schema --no-spec definitions/photoshelter.json'
        - 'sleep 3'
      install: skip
    -
      stage: contract-testing
      verbose: true
      script:
        - 'prism mock definitions/photoshelter.json'
        - 'sleep 1'
        - 'dredd http://localhost:4010/photoshelter.json'
    -
      stage: documentation
      deploy: null
      verbose: true
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      keep_history: true
      project_name: psapi-v4-doc.github.io
      public_repo: "photoshelter-dev/psapi-v4-doc.github.io\non:\n  branch: master"
      script:
        - ./run-redoc.exp
        - 'ls -la'
        - 'npm run gh-pages'
        - pwd
        - 'ls -la'
        - 'sleep 3'
