dist: trusty
language: node_js
node_js: 
  - "9"
before_install: 
  - "npm install"
  - "npm install redoc --save"
  - "npm install -g create-openapi-repo"
  - "sudo apt-get install expect"
  - "sudo apt-get install curl"
before_script: 
  - "sudo chmod 755 run-redoc.exp"
  - "cat /etc/hosts"
  - "curl -I -v https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/.travis.yml"
after_scritp:
  - "wget https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/index.html"
cache: 
  directories: 
    - node_modules

env:
  global:
    - secure: "On82Or3P6h3hKhblckPiZVzgeWLlEs/yCMGCxsBYAu9xcuexGscHCqL0XCHre1dvu8mUrUkCmkV1qxz7miUJ/qSdgPlYQy7bejwWcvW1oX6Cc4on3Oi23pRUBditojNOcBxMwC8V5ddRQe6otiQqs6xG4Y2tnh9epUzlsG2DgBW7rIWyXpZniV6447RQoL9eBTx+liFJk6qFOXo0Ds51GO1Juy/rM1fyVXmrkpdundF+xqr6JhbmIklgqlAUPDTHltR4pFWZO0lT+TpGPViBeiedYp84PKaOXy7fsOl46zrEP9e1MErmhxM+3XLChkUKOikLys+TxC2HcUoLN46mblmDhq//Zn1M+2MK79WRdFPhqGGlFlTQiyPw0up5SSCbaVdP27Obe2C93iHo6+LDoVH/AsR21rfxyycJ0pc8xLr4tSDrEmgVlJNP/kTfOGgmgYelP8s1s1siDxriEAW1YXYpSmDZ7c2qDzeGDB35Gt7kldWN9eI0/Eymv5IXW2psVLwzZOncixSVHKMRwXTiOvWHeUs6/rHE4kshzgBnrDW78XOczxzJDJt/00V09ydL1kz9om9eO/ZrQV9eFFDO6Js7LCk0VreTYrVxwN9DKVcXSMNXBiFKbLm8d3FrW/TRz8+78PY8ufasKa2WEROALHRxqMXm/Dh/fyf4+P9feEY="

deploy:
  verbose: true
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  project_name: psapi-v4-doc.github.io
#  repo: photoshelter-dev/psapi-v4-doc.github.io
  public_repo: photoshelter-dev/psapi-v4-doc.github.io
  on:
    branch: master
script: 
  - ./run-redoc.exp
  - "ls -la"
  - "cat json-resolved/photoshelter.json"
  - "npm run gh-pages"
  - pwd
  - "ls -la"
  - "sleep 3"
sudo: required
