dist: trusty
language: node_js
node_js: 
  - "9"
before_install: 
  - "npm install"
  - "npm install -g swagger-cli"
  - "npm install redoc --save"
  - "npm install -g create-openapi-repo"
  - "sudo apt-get install expect"
  - "sudo apt-get install curl"
before_script: 
  - "sudo chmod 755 run-redoc.exp"
  - "cat /etc/hosts"
  - "curl -I -v https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/.travis.yml"
after_scritp:
  - "wget https://github.com/photoshelter-dev/psapi-v4-doc.github.io/blob/master/index.html"
  - "ls -la"
#  - "swagger-cli validate -d --no-schema --no-spec json-resolved/photoshelter.json"
cache: 
  directories: 
    - node_modules
    
deploy:
  verbose: true
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  project_name: psapi-v4-doc.github.io
  public_repo: photoshelter-dev/psapi-v4-doc.github.io
  on:
    branch: master
script: 
  - ./run-redoc.exp
  - "ls -la"
  - "npm run gh-pages"
  - pwd
  - "ls -la"
  - "sleep 3"
sudo: required
