gallery_id:
  name: gallery_id
  description: "The ID of the gallery"
  example: "G0000EXAMPLEGALL"
  in: path
  required: true
  schema:
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^G0000[a-zA-Z0-9._]{11}$'
    example: 'G0000EXAMPLEGALL'
    description: 'The Gallery ID'

gallery_id_query:
  name: gallery_id
  description: "The ID of the gallery"
  example: "G0000EXAMPLEGALL"
  in: query
  required: false
  schema:
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^G0000[a-zA-Z0-9._]{11}$'
    example: 'G0000EXAMPLEGALL'
    description: 'The Gallery ID'

collection_id:
  name: collection_id
  in: path
  required: true
  schema:
    description: 'My collection description'
    title: 'My Collection Test'
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^C0000[a-zA-Z0-9._]{11}$'
    example: C0000c1x4UMGPvkY
  description: 'The Collection ID'

child_collection_id:
  name: child_collection_id
  in: path
  required: true
  schema:
    description: 'My collection description'
    title: 'My Collection Test'
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^C0000[a-zA-Z0-9._]{11}$'
    example: C0000c1x4UMGPvkY
  description: 'The Collection ID'

collection_id_query:
  name: collection_id
  in: query
  required: false
  schema:
    description: 'My collection description'
    title: 'My Collection Test'
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^C0000[a-zA-Z0-9._]{11}$'
    example: C0000c1x4UMGPvkY
  description: 'The Collection ID'

match:
  name: match
  in: query
  description: Flag that denotes whether to perform a partial name match. This
    parameter will only work if the name query parameter has been set and the
    only value available for this parameter is false. Setting this parameter
    to false will perform case insensitive partial name matching.
  required: false
  style: form
  explode: true
  schema:
    type: boolean
    default: false
    enum:
    - false
    - true
  example: false

media_id:
  name: media_id
  description: "ID of the media"
  example: "I0000EXAMPLEIMAG"
  in: query
  required: false
  schema:
    type: string
    pattern: '^(VD|AD|I0|DO)000[a-zA-Z0-9._]{11}$'

org_id:
  name: org_id
  description: "Organization id to perform the search on"
  example: "O0000EXAMPLE_ORG"
  in: query
  required: false
  schema:
    type: string
    pattern: '^O0000[a-zA-Z0-9._]{11}$'

page:
  name: page
  in: query
  description: 'The number of items to skip before returning the results'
  example: 1
  required: false
  schema:
    type: integer
    minimum: 0
    maximum: 999
    default: 0

per_page:
  name: per_page
  in: query
  description: 'The number of items to return'
  example: 20
  required: false
  schema:
    type: integer
    format: int32
    minimum: 50
    maximum: 500
    default: 50

sort_direction:
  name: sort_direction
  in: query
  description: Sort direction. This parameter requires the usage of the 'sort_by'
    query parameter. Setting this parameter to one of the allowed values will
    set the direction of the sort.
  required: false
  style: form
  explode: true
  schema:
    type: string
    enum:
    - ascending
    - descending
  example: ascending

user_id:
  name: user_id
  description: "User id to perform the search on"
  example: "U0000EXAMPLEUSER"
  in: query
  required: false
  schema:
    type: string
    pattern: '^U0000[a-zA-Z0-9._]{11}$'
