gallery_id:
  name: gallery_id
  description: "The ID of the gallery"
  example: "G0000EXAMPLEGALL"
  in: path
  required: true
  schema:
    type: string
    minLength: 16
    maxLength: 16
    pattern: '^G0000[a-zA-Z0-9._]{11}$'
    example: 'G0000EXAMPLEGALL'
    description: 'The Gallery ID'

match:
  name: match
  in: query
  description: Flag that denotes whether to perform a partial name match. This
    parameter will only work if the name query parameter has been set and the
    only value available for this parameter is false. Setting this parameter
    to false will perform case insensitive partial name matching.
  required: false
  style: form
  explode: true
  schema:
    type: boolean
    default: false
    enum:
    - false
    - true
  example: false

page:
  name: page
  in: query
  description: 'The number of items to skip before returning the results'
  example: 1
  required: false
  schema:
    type: integer
    minimum: 0
    maximum: 999
    default: 0

per_page:
  name: per_page
  in: query
  description: 'The number of items to return'
  example: 20
  required: false
  schema:
    type: integer
    format: int32
    minimum: 50
    maximum: 500
    default: 50

sort_direction:
  name: sort_direction
  in: query
  description: Sort direction. This parameter requires the usage of the 'sort_by'
    query parameter. Setting this parameter to one of the allowed values will
    set the direction of the sort.
  required: false
  style: form
  explode: true
  schema:
    type: string
    enum:
    - ascending
    - descending
  example: ascending
