openapi: 3.0.0
info:
  title: PhotoShelter API v4
  description: '# PhotoShelter API v4 definition'
  termsOfService: https://www.photoshelter.com/support/terms/
  contact:
    name: PhotoShelter API Support Team
    url: https://support.photoshelter.com
    email: api-support@photoshelter.com
  license:
    name: PhotoShelter License
    url: https://www.photoshelter.com/support/license
  version: Allan
servers:
- url: https://virtserver.swaggerhub.com/PhotoShelter/PhotoShelter/4
  description: PhotoShelter Auto Mocking API
tags:
- name: PhotoShelter API
paths:
  /collections/{collection_id}/link:
    get:
      tags:
      - Collection
      summary: GET /collections/{collection_id}/link.
      description: Get a collection's link
      operationId: collectionsGetIdLink
      parameters:
      - name: collection_id
        in: path
        description: Collection ID to retrieve a link from
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/CollectionId'
        example: C0000EXAMPLECOLL
      responses:
        200:
          description: ok
components:
  schemas:
    CollectionId:
      maxLength: 16
      minLength: 16
      pattern: ^C0000[a-zA-Z0-9._]{11}$
      type: string
      description: The Collection ID
      example: C0000EXAMPLECOLL
