openapi: 3.0.0
info:
  title: PhotoShelter API v4
  description: '# PhotoShelter API v4 definition'
  termsOfService: https://www.photoshelter.com/support/terms/
  contact:
    name: PhotoShelter API Support Team
    url: https://support.photoshelter.com
    email: api-support@photoshelter.com
  license:
    name: PhotoShelter License
    url: https://www.photoshelter.com/support/license
  version: Yemi
servers:
- url: https://virtserver.swaggerhub.com/PhotoShelter/PhotoShelter/4
  description: PhotoShelter Auto Mocking API
tags:
- name: Authenticate
paths:
  /authenticate:
    get:
      summary: Use your PhotoShelter credentials to log in to your account.
      description: Verify user is a member.
      operationId: authenticate-get
      parameters:
      - name: api_key
        in: query
        description: The API Key. Can be requested if you do not have one.
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/ApiKey'
      responses:
        200:
          description: |
            /galleries/{gallery_id} - HTTP 200 OK Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                data:
                  type: gallery
                  id: G0000EXAMPLE_GAL
                  attributes:
                    name: Example Name
                    description: Example Description
                    display_order: 10
                    key_image_id: GI000EXAMPLE_IMG
                    access_id: A0000EXAMPLE_ACS
                    is_listed: false
                    is_orig_enabled: false
                    is_watermark_disabled: false
                    created_at: 2019-04-09T18:34:40-04:00
                    modified_at: 2019-09-06T16:24:24-04:00
                  links:
                    self: example.photoshelter.com/galleries/G0000EXAMPLE_GAL
                meta:
                  copyright: PhotoShelter 2019
                  version: 2019-05-01
                  rate_limit_limit: 10
                  rate_limit_current: 1
                  rate_limit_expires: 40
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          links:
            GetGallery:
              operationId: galleryGetId
              parameters:
                gallery_id: $response.body#/data/id
              description: Links to self
    post:
      summary: Use your PhotoShelter credentials to log in to your account.
      description: Verify user is a member.
      operationId: authenticate
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        200:
          description: response
          content:
            text/html:
              schema:
                type: string
  /authenticate/logout:
    get:
      summary: Log out of PhotoShelter.
      description: Log our of PhotoShelter
      operationId: logout
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: object
      - name: X-PS-Auth-Token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: object
      responses:
        200:
          description: Generic HTTP 200 Ok Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
    post:
      summary: Log out of PhotoShelter.
      description: Log out of PhotoShelter
      operationId: logout_post
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: object
      - name: X-PS-Auth-Token
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: object
      responses:
        200:
          description: Generic HTTP 200 Ok Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
components:
  schemas:
    ApiKey:
      type: string
    Gallery:
      required:
      - attributes
      - id
      - type
      type: object
      properties:
        id:
          pattern: ^G0000[a-zA-Z0-9._]{11}$
          type: string
          description: Gallery ID
          example: G0000EXAMPLE_GAL
          xml:
            attribute: true
        type:
          pattern: gallery
          type: string
          example: gallery
        attributes:
          $ref: '#/components/schemas/Gallery_attributes'
        links:
          $ref: '#/components/schemas/Gallery_links'
    MetaTag:
      type: object
      properties:
        copyright:
          type: string
          example: PhotoShelter 2019
        version:
          type: string
          example: 2019-05-01
        rate_limit_limit:
          type: integer
          example: 10
        rate_limit_current:
          type: integer
          example: 1
        rate_limit_expires:
          type: integer
          example: 60
    inline_response_200:
      required:
      - data
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Gallery'
        meta:
          $ref: '#/components/schemas/MetaTag'
    body:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          format: email
    inline_response_200_1_meta:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          example: OK
    inline_response_200_1:
      required:
      - meta
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/inline_response_200_1_meta'
    Gallery_attributes:
      required:
      - access_id
      - created_at
      - description
      - display_order
      - is_listed
      - is_orig_enabled
      - is_watermark_disabled
      - key_image_id
      - modified_at
      - name
      - name_url
      type: object
      properties:
        name:
          maxLength: 100
          type: string
          description: Name of Gallery or Collection object (Whichever it is)
          example: My trip to DR
        name_url:
          maxLength: 100
          type: string
          description: URL to the gallery
          nullable: true
        description:
          maxLength: 100
          type: string
          description: Description of the Gallery
          nullable: true
          example: Trip to DR with my brothers and sisters
        display_order:
          type: integer
          description: Custom display order
          example: 1
        key_image_id:
          pattern: ^GI000[a-zA-Z0-9._]{11}$
          type: string
          description: ID of the Image that is the key image
          nullable: true
          example: GI000EXAMPLE_IMG
        access_id:
          pattern: ^A0000[a-zA-Z0-9._]{11}$
          type: string
          description: Access ID of the Gallery
          example: A0000EXAMPLE_ACS
        is_listed:
          type: boolean
          description: Flag that denotes if it is listed on the public site
          example: false
        is_orig_enabled:
          type: boolean
          description: Original enabled boolean value
          example: true
        is_watermark_disabled:
          type: boolean
          description: Watermark disabled boolean value
          example: true
        created_at:
          type: string
          description: Creation date
          example: 2019-04-25T14:54:12.136828
        modified_at:
          type: string
          description: Last modified date
          example: 2019-04-25T14:54:12.136828
    Gallery_links:
      type: object
      properties:
        self:
          type: string
          description: Link to itself
          example: https://api.photoshelter.com/psapi/v4/galleries/G0000ZJCk9LW4Zfc
