openapi: 3.0.0
info:
  title: PhotoShelter API v4
  description: '# PhotoShelter API v4 definition'
  termsOfService: https://www.photoshelter.com/support/terms/
  contact:
    name: PhotoShelter API Support Team
    url: https://support.photoshelter.com
    email: api-support@photoshelter.com
  license:
    name: PhotoShelter License
    url: https://www.photoshelter.com/support/license
  version: Yemi
servers:
- url: https://virtserver.swaggerhub.com/PhotoShelter/PhotoShelter/4
  description: PhotoShelter Auto Mocking API
tags:
- name: Authenticate
paths:
  /authenticate:
    get:
      summary: Use your PhotoShelter credentials to log in to your account.
      description: Verify user is a member.
      operationId: authenticate-get
      parameters:
      - name: api_key
        in: query
        description: The API Key. Can be requested if you do not have one.
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: email
        in: query
        description: Email Address
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: email
      - name: mode
        in: query
        description: token or cookie
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
    post:
      summary: Use your PhotoShelter credentials to log in to your account.
      description: Verify user is a member.
      operationId: authenticate
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        200:
          description: response
          content:
            text/html:
              schema:
                type: string
  /authenticate/logout:
    get:
      summary: Log out of PhotoShelter.
      description: Log our of PhotoShelter
      operationId: logout
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: object
      - name: X-PS-Auth-Token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: object
      responses:
        200:
          description: Generic HTTP 200 Ok Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
    post:
      summary: Log out of PhotoShelter.
      description: Log out of PhotoShelter
      operationId: logout_post
      parameters:
      - name: X-PS-Api-Key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: object
      - name: X-PS-Auth-Token
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: object
      responses:
        200:
          description: Generic HTTP 200 Ok Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
components:
  schemas:
    inline_response_200_1_meta:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          example: OK
    inline_response_200_1:
      required:
      - meta
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/inline_response_200_1_meta'
    inline_response_200:
      type: object
      properties:
        api_token:
          type: string
    body:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        mode:
          type: string
