openapi: 3.0.0
info:
  title: PhotoShelter API v4
  description: '# PhotoShelter API v4 definition'
  termsOfService: https://www.photoshelter.com/support/terms/
  contact:
    name: PhotoShelter API Support Team
    url: https://support.photoshelter.com
    email: api-support@photoshelter.com
  license:
    name: PhotoShelter License
    url: https://www.photoshelter.com/support/license
  version: Chung
servers:
- url: https://virtserver.swaggerhub.com/PhotoShelter/PhotoShelter/4
  description: PhotoShelter Auto Mocking API
paths:
  /galleries/{gallery_id}:
    delete:
      tags:
      - Galleries
      summary: Delete a gallery.
      description: Delete a gallery.
      operationId: galleryDeleteId
      parameters:
      - name: gallery_id
        in: path
        description: Gallery ID
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/schema'
      responses:
        200:
          description: Generic HTTP 200 Ok Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        400:
          description: 400 Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 401 Unauthorized Client Error
          headers:
            WWW-Authenticate:
              description: The HTTP WWW-Authenticate response header defines the authentication
                method that should be used to gain access to a resource.
              style: simple
              explode: false
              schema:
                type: string
              example: 'WWW-Authenticate: Bearer'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: 403 Forbidden Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: 404 Not Found Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        429:
          description: 429 Too Many Requests Error
          headers:
            Retry-After:
              description: The Retry-After response HTTP header, expressed in seconds,
                indicates how long the user agent should wait before making a follow-up
                request.
              style: simple
              explode: false
              schema:
                type: integer
              example: 180
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /media/{media_id}/download:
    get:
      tags:
      - Media
      summary: Get the media with the associated ID.
      description: Get the media with the associated ID.
      operationId: mediaDownloadGetId
      parameters:
      - name: media_id
        in: path
        description: Media ID
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/schema_2'
      responses:
        200:
          description: Download - HTTP OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: 400 Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 401 Unauthorized Client Error
          headers:
            WWW-Authenticate:
              description: The HTTP WWW-Authenticate response header defines the authentication
                method that should be used to gain access to a resource.
              style: simple
              explode: false
              schema:
                type: string
              example: 'WWW-Authenticate: Bearer'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: 403 Forbidden Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: 404 Not Found Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        429:
          description: 429 Too Many Requests Error
          headers:
            Retry-After:
              description: The Retry-After response HTTP header, expressed in seconds,
                indicates how long the user agent should wait before making a follow-up
                request.
              style: simple
              explode: false
              schema:
                type: integer
              example: 180
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /library:
    get:
      tags:
      - Library
      summary: Retrieve library listing.
      description: Retrieve library listing.
      operationId: libraryGet
      parameters:
      - name: listed
        in: query
        description: listed or unlisted
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/schema_2'
      responses:
        200:
          description: |
            /library - HTTP 200 OK Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
            application/xml:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        400:
          description: 400 Bad Request Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: 401 Unauthorized Client Error
          headers:
            WWW-Authenticate:
              description: The HTTP WWW-Authenticate response header defines the authentication
                method that should be used to gain access to a resource.
              style: simple
              explode: false
              schema:
                type: string
              example: 'WWW-Authenticate: Bearer'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        403:
          description: 403 Forbidden Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
        429:
          description: 429 Too Many Requests Error
          headers:
            Retry-After:
              description: The Retry-After response HTTP header, expressed in seconds,
                indicates how long the user agent should wait before making a follow-up
                request.
              style: simple
              explode: false
              schema:
                type: integer
              example: 180
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                errors: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    schema:
      title: My Gallery Test
      maxLength: 16
      minLength: 16
      pattern: ^G0000[a-zA-Z0-9._]{11}$
      type: string
      description: My gallery description
      example: G0000EXAMPLE_GAL
    Error:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error_errors'
      description: This object generates errors in compliance with RFC 7807 API Problem
    schema_2:
      title: Media ID
      maxLength: 16
      minLength: 16
      pattern: ^(AD|VD|DO|I0)000[a-zA-Z0-9._]{11}$
      type: string
      description: Media ID
      example: G0000EXAMPLE_GAL
    ArrayOfGalleries:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Gallery'
    ArrayOfCollections:
      type: array
      items:
        allOf:
        - $ref: '#/components/schemas/Collection'
    MetaTag:
      type: object
      properties:
        copyright:
          type: string
          example: PhotoShelter 2019
        version:
          type: string
          example: 2019-05-01
        rate_limit_limit:
          type: integer
          example: 10
        rate_limit_current:
          type: integer
          example: 1
        rate_limit_expires:
          type: integer
          example: 60
    inline_response_200_meta:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          example: OK
    inline_response_200:
      required:
      - meta
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/inline_response_200_meta'
    inline_response_200_1:
      required:
      - collections
      - galleries
      type: object
      properties:
        galleries:
          $ref: '#/components/schemas/ArrayOfGalleries'
        collections:
          $ref: '#/components/schemas/ArrayOfCollections'
        meta:
          $ref: '#/components/schemas/MetaTag'
    Error_links:
      type: object
      properties:
        about:
          type: string
          example: http://api.developer.com/404.html
    Error_errors:
      type: object
      properties:
        id:
          type: string
          description: A unique identifier for this occurrence of the problem
        links:
          $ref: '#/components/schemas/Error_links'
        title:
          type: string
          description: A short, human-readable summary of the problem type
        status:
          type: string
          description: The HTTP status code set by the origin server for this occurrence
            of the problem.
        detail:
          type: string
          description: An human readable explanation specific to this occurrence of
            the problem.
