<?php
/**
 * CollectionAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhotoShelter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhotoShelter API v4
 *
 * # PhotoShelter API v4 definition
 *
 * OpenAPI spec version: Anthony
 * Contact: api-support@photoshelter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhotoShelter;

/**
 * CollectionAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description CollectionAttributes
 * @package     PhotoShelter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CollectionAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CollectionAttributes"
     */
    public function testCollectionAttributes()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_url"
     */
    public function testPropertyNameUrl()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "display_order"
     */
    public function testPropertyDisplayOrder()
    {
    }

    /**
     * Test attribute "key_image_id"
     */
    public function testPropertyKeyImageId()
    {
    }

    /**
     * Test attribute "access_id"
     */
    public function testPropertyAccessId()
    {
    }

    /**
     * Test attribute "is_listed"
     */
    public function testPropertyIsListed()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "modified_at"
     */
    public function testPropertyModifiedAt()
    {
    }
}
