<?php
/**
 * PaginationMetaTagTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  PhotoShelter
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhotoShelter API v4
 *
 * # PhotoShelter API v4 definition
 *
 * OpenAPI spec version: Anthony
 * Contact: api-support@photoshelter.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace PhotoShelter;

/**
 * PaginationMetaTagTest Class Doc Comment
 *
 * @category    Class
 * @description PaginationMetaTag
 * @package     PhotoShelter
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaginationMetaTagTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaginationMetaTag"
     */
    public function testPaginationMetaTag()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "first"
     */
    public function testPropertyFirst()
    {
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
    }

    /**
     * Test attribute "next"
     */
    public function testPropertyNext()
    {
    }

    /**
     * Test attribute "prev"
     */
    public function testPropertyPrev()
    {
    }
}
