openapi: 3.0.0
info:
  license:
    name: 'PhotoShelter License'
    url: 'https://www.photoshelter.com/support/license'
  contact:
    name: PhotoShelter API Support Team
    url:  https://support.photoshelter.com
    email: 'api-support@photoshelter.com'
  version: '4'
  title: 'PhotoShelter API v4'
  description: '# PhotoShelter API v4 definition'
  termsOfService: "https://www.photoshelter.com/support/terms/"


# Added by API Auto Mocking Plugin
servers:
  - description: PhotoShelter Auto Mocking API
    url: https://virtserver.swaggerhub.com/PhotoShelter/PhotoShelter/4


paths:
  /collection:
    get:
      operationId: GetCollection
      description: "Gets all the collections for the account!"
      summary: "Gets all the collections for the account."
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: If provided, the endpoint will returns the requested data page if available.
        - in: query
          name: per_page
          schema:
            type: integer
          required: false
          description: If provided. the endpoint will return the requested data limited by the value of per_page
      responses:
        '200':
          description: HTTP OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/v1JsonApi'
                  - properties:
                      data:
                        oneOf:
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Gallery'
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Image'
                      meta:
                        $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/MetaTag'
                    
  /galleries:
    get:
      operationId: GalleryGet
      description: "Gets all the galleries for the account!"
      summary: "Gets all the galleries for the account."
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: If provided, the endpoint will returns the requested data page if available.
        - in: query
          name: per_page
          schema:
            type: integer
          required: false
          description: If provided. the endpoint will return the requested data limited by the value of per_page
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/v1JsonApi'
                  - properties:
                      data:
                        oneOf:
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Gallery'
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Image'
                      meta:
                        $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/MetaTag'

  
  /galleries/{gallery_id}:
    get:
      x-code-samples:
        lang: "PHP"
        label: "PHP 7.1"
        source: 'echo "ITS A TRAP!";'  
      operationId: GalleryGetId
      description: "/galleries/{gallery_id} - Get gallery data based off gallery id"
      summary: "Get gallery data based off gallery id."
      parameters:
          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4.1#/components/parameters/gallery_id'
          - in: query
            name: include
            schema:
              title: string
              description: "ITS A TRAP."
              pattern: "[a-zA-Z]"
              enum: # how to transpose this into the domain and make it 'dynamic'?
                - children
                - images, images.iptc, images.xmp
                - cover
                - count
     #     - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/page'
     #     - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/per_page'
      #    - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/date_format'
    #      - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/include'

      responses:
        '200':
          description: HTTP OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/v1JsonApi'
                  - properties:
                      data:
                        oneOf:
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Gallery'
                          - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Image'
                      meta:
                        $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/MetaTag'
    patch:
      operationId: GalleryUpdateId
      description: "Update the gallery at that id."
      summary: "Update the gallery at that id."
      parameters:
        - in: path
          name: gallery_id
          schema:
              $ref: "https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/gallery_id/schema"
          required: true
          description: The Gallery ID
        - in: header
          name: name
          schema:
            type: string
          required: false
          description: Gallery name
        - in: header
          name: description
          schema:
            type: string
          required: false
          description: Gallery description
        - in: header
          name: f_list
          schema:
            type: boolean
          required: false
          description: Boolean value denoting if it's listed on public site
      responses:
        '200':
          description: HTTP OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      gallery_id:
                        $ref: "https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/gallery_id/schema"
                  meta:
                    type: object
    delete:
      operationId: GalleryDeleteId
      description: "Delete a gallery."
      summary: "Delete a gallery."
      parameters:
        - in: path
          name: gallery_id
          schema:
            $ref: "https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/parameters/gallery_id/schema"
          required: true
          description: Gallery ID
      responses:
        '200':
          description: HTTP OK

  /gallery/search:
    get: 
      operationId: GallerySearch
      description: "Search galleries for the account"
      summary: "Retrieve a subset of galleries via parameters."
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: If provided, search for galleries by the name
        - in: query
          name: parent
          schema:
            type: string
          required: false
          description: If provided, limit galleries to children of the provided collection ID
        - in: query
          name: sort_by
          schema:
            type: string
            enum:
              - creation_time
              - modification_time
              - name
              - display_order
          required: false
          description: If provided, gives a field to sort by
        - in: query
          name: sort_dir
          schema:
            type: string
            enum:
              - asc
              - desc
          required: false
          description: If provided, gives an order to sort by
        - in: query
          name: per_page
          schema:
            type: integer
          required: false
          description: If provided, defines the number of results per age
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: If provided, defines the current page number
      responses:
        '200':
          description: HTTP OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - OK
                      - error
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 1
                      galleries:
                        type: array
                        items: {}
                        #  $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PS-API/4#/components/schemas/Gallery'
  
  # Lets put this one on hold
  /gallery/insert:
    post:
      operationId: GalleryInsert
      description: "Insert a gallery"
      summary: "Insert a gallery."
      parameters:
        - in: header
          name: name
          schema:
            type: string
          required: false
          description: Gallery name
        - in: header
          name: description
          schema:
            type: string
          required: false
          description: Gallery description
        - in: header
          name: f_list
          schema:
            type: boolean
          required: false
          description: Boolean denoting if gallery is listed on public site
        - in: header
          name: mode
          schema:
            type: string
            enum:
              - private
              - permission
              - everyone
          required: false
          description: Visibility mode
        - in: header
          name: native_mode
          schema:
            type: string
            enum:
              - private
              - permission
              - everyone
          required: false
          description: Native visibility mode of the specific gallery
      responses:
        '200':
          description: HTTP OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - OK
                      - error
                  data:
                    type: object
                    properties:
                      gallery:
                        type: string
                        pattern: '^G0000[a-zA-Z0-9]{11}$'
                        example: G0000ZJCk9LW4Zfc
  /media/{media_id}:
    get:
      operationId: Media Get
      description: "Get the media with the associated ID."
      summary: "Get the media with the associated ID."
      parameters:
        - in: path
          name: media_id
          schema:
            type: string
            enum:
              - ok
          required: true
          description: "Media"
      responses:
        '200':
          $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/responses/Response'
components:
  schemas:
    ApiProblem:
      description: This object generates errors in compliance with RFC 7807 'API Problem'
      properties:
        title:
          description: 'A short, human-readable summary of the problem type'
          type: string
        type:
          description: A URI reference (RFC3986) that identifies the problem type
          type: string
        status:
          description: The HTTP status code set by the origin server for this occurrence of the problem.
          type: integer
        detail:
          description: An human readable explanation specific to this occurrence of the problem.
          type: string
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          type: string
      type: object
    v1JsonApi:
      description: A flat schema for the JSONAPI-light
      properties:
        data:
          type: object
          oneOf:
            - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Gallery'
            - $ref: 'https://api.swaggerhub.com/domains/PhotoShelter/PhotoShelter-Domain/4#/components/schemas/Image'
          example: {}
        meta:
          description: ''
          type: object
        errors:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/ApiProblem'
      type: object